import turtle as t
t.bgcolor('#23153E')
def pumpkin(x,y):
  t.pu()
  t.goto(x-50,y)
  t.pd()
  t.pencolor("Dark Orange")
  t.pensize(3)
  t.fillcolor("Dark Orange")
  t.begin_fill()
  t.circle(50)
  t.end_fill()
  t.pu()
  t.goto(x,y)
  t.pd()
  t.fillcolor("Dark Orange")
  t.begin_fill()
  t.circle(50)
  t.end_fill()
  t.goto(x-25,y+95)
  t.pensize(10)
  t.pencolor("Dark Green")
  t.circle(10,200)
pumpkin(0,0)
t.pu()
t.goto(-75,-50)
t.pd()
t.pencolor("Light Green")
t.write("Happy Halloween!")
t.hideturtle()