import turtle as t
def halftriangestar(fillcolor,pencolor,pensize):
  t.fillcolor(fillcolor)
  t.pencolor(pencolor)
  t.pensize(pensize)
  t.begin_fill()
  t.lt(45)
  t.fd(40)
  t.lt(70)
  t.fd(60)
  t.lt(155)
  t.fd(85)
  t.end_fill()
  t.fillcolor(fillcolor)
  t.pencolor(pencolor)
  t.pensize(pensize)
  t.begin_fill()
  t.lt(90)
  t.fd(70)
  t.rt(150)
  t.fd(45)
  t.rt(60)
  t.fd(40)
  t.end_fill()
def reversehalftriangestar(fillcolor,pencolor,pensize):
  t.fillcolor(fillcolor)
  t.pencolor(pencolor)
  t.pensize(pensize)
  t.begin_fill()
  t.rt(45)
  t.fd(40)
  t.rt(70)
  t.fd(60)
  t.rt(155)
  t.fd(85)
  t.end_fill()
  t.fillcolor(fillcolor)
  t.pencolor(pencolor)
  t.pensize(pensize)
  t.begin_fill()
  t.lt(100)
  t.fd(70)
  t.lt(150)
  t.fd(45)
  t.lt(60)
  t.fd(40)
  t.end_fill()
for i in range(2):
  halftriangestar("yellow", "yellow", "12")
  t.lt(35)
t.goto(-3,0)
t.rt(5)
for i in range(2):
  reversehalftriangestar("orange", "orange", "10")
  t.lt(135)
