import turtle as t


def olympic_circles():
  t.penup()
  t.goto(0, 0)
  t.pensize(5)
  t.pendown()
  t.pencolor("black")
  t.circle(15)
  t.penup()
  t.goto(15, -15)
  t.pencolor("light green")
  t.pendown()
  t.circle(15)
  t.penup()
  t.goto(30, 0)
  t.pencolor("purple")
  t.pendown()
  t.circle(15)
  t.penup()
  t.goto(-30, 0)
  t.pencolor("yellow")
  t.pendown()
  t.circle(15)
  t.penup()
  t.goto(-15, -15)
  t.pencolor("blue")
  t.pendown()
  t.circle(15)


def dart_board():
  dart_board_circle_size = 0
  for i in range(4):
    t.penup()
    t.goto(0, -1 * dart_board_circle_size)
    t.pendown()
    t.circle(dart_board_circle_size + 30)
    dart_board_circle_size += 30


def sun():
  t.fillcolor("red")
  t.begin_fill()
  t.penup()
  t.goto(0, -100)
  t.pendown()
  t.circle(100)
  t.end_fill()
  t.penup()
  t.goto(0, -125)
  t.rt(90)
  t.pendown()
  t.fd(50)
  t.lt(180)
  t.penup()
  t.goto(0, 125)
  t.pendown()
  t.fd(50)
  t.penup()
  t.goto(125, 0)
  t.rt(90)
  t.pendown()
  t.fd(50)
  t.penup()
  t.goto(-125, 0)
  t.lt(180)
  t.pendown()
  t.forward(50)
  t.penup()
  t.goto(-100, 70)
  t.rt(25)
  t.pendown()
  t.fd(50)
  t.penup()
  t.goto(100, -70)
  t.lt(180)
  t.pendown()
  t.fd(50)
  t.penup()
  t.goto(70, -100)
  t.rt(25)
  t.pendown()
  t.fd(50)
  t.rt(180)
  t.penup()
  t.goto(-70, 100)
  t.pendown()
  t.fd(50)
  t.penup()
  t.goto(70, 100)
  t.rt(90)
  t.pendown()
  t.fd(50)
  t.penup()
  t.goto(-70, -100)
  t.pendown()
  t.forward(-50)
  t.penup()
  t.goto(-100, -70)
  t.lt(155)
  t.pendown()
  t.forward(50)
  t.penup()
  t.goto(100, 70)
  t.rt(180)
  t.pendown()
  t.forward(50)


#type a command by deleting the hash from the below:
#sun()
olympic_circles()
#dart_board()
